# Generated by Django 2.1.5 on 2019-03-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=105)),
                ('Description', models.TextField()),
                ('ContactNumber', models.CharField(max_length=11)),
                ('Date_lost', models.DateTimeField()),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('Address1', models.CharField(max_length=105)),
                ('Address2', models.CharField(max_length=105)),
                ('Address3', models.CharField(max_length=105)),
            ],
        ),
    ]
