# Generated by Django 2.1.5 on 2019-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finder',
            name='Address4',
            field=models.CharField(blank='True', default='Null', max_length=105),
        ),
        migrations.AddField(
            model_name='finder',
            name='Address5',
            field=models.CharField(blank='True', default='Null', max_length=105),
        ),
        migrations.AddField(
            model_name='finder',
            name='image4',
            field=models.ImageField(blank='True', default='Null', upload_to=''),
        ),
        migrations.AddField(
            model_name='finder',
            name='image5',
            field=models.ImageField(blank='True', default='Null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='finder',
            name='image3',
            field=models.ImageField(blank='True', default='Null', upload_to=''),
        ),
    ]
