# Generated by Django 2.0.7 on 2019-03-25 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20190324_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finder',
            name='Address1',
        ),
        migrations.AddField(
            model_name='finder',
            name='Address1',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
