# Generated by Django 2.0.7 on 2019-03-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190325_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='finder',
            old_name='Address1',
            new_name='TrackAddress',
        ),
        migrations.RenameField(
            model_name='finder',
            old_name='image1',
            new_name='TrackImage',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='Address3',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='Address4',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='Address5',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='finder',
            name='image5',
        ),
        migrations.AddField(
            model_name='trackaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.finder'),
        ),
    ]
