# Generated by Django 2.0.7 on 2019-03-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190325_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackAddress',
            new_name='Address',
        ),
    ]
