# Generated by Django 2.0.7 on 2019-03-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190325_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='finder',
            name='Photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
