# Generated by Django 2.0.7 on 2019-03-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190325_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
    ]
