# Generated by Django 2.0.7 on 2019-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190325_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finder',
            name='TrackImage',
        ),
        migrations.AddField(
            model_name='finder',
            name='TrackImage',
            field=models.ImageField(default=1, upload_to='', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
