# Generated by Django 2.0.7 on 2019-03-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190325_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder',
            name='TrackImage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Images'),
        ),
    ]
