# Generated by Django 2.1.7 on 2019-03-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190325_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finder',
            old_name='Photo',
            new_name='image',
        ),
    ]
