# Generated by Django 2.0.4 on 2019-03-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190325_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder',
            name='TrackAddress',
            field=models.ManyToManyField(blank=True, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='finder',
            name='TrackImage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Images'),
        ),
    ]
